# Generated by Django 2.1.7 on 2019-03-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDung', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loaitin',
            fields=[
                ('idLoaiTin', models.IntegerField(primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=255)),
                ('TenKhongDau', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('idSlide', models.IntegerField(primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=255)),
                ('Hinh', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='theloai',
            fields=[
                ('idTheLoai', models.IntegerField(primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=255)),
                ('TenKhongDau', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('idTin', models.IntegerField(primary_key=True, serialize=False)),
                ('TieuDe', models.CharField(max_length=255)),
                ('TieuDeKhongDau', models.CharField(max_length=255)),
                ('TomTat', models.TextField()),
                ('NoiDung', models.TextField()),
                ('Hinh', models.CharField(max_length=255)),
                ('NoiBat', models.IntegerField(max_length=11)),
                ('SoLuotXem', models.IntegerField(max_length=11)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
                ('idLoaiTin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinTuc.loaitin')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(blank=True, null=True)),
                ('Update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loaitin',
            name='idTheLoai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinTuc.theloai'),
        ),
        migrations.AddField(
            model_name='comment',
            name='idTinTuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinTuc.Tin'),
        ),
        migrations.AddField(
            model_name='comment',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinTuc.users'),
        ),
    ]
